const sampleIntegrations = [
  {
    id: "api-invenio-release",
    name: "Central Library Invenio Sync",
    institution: "North Coast University",
    integrationType: "institutional_repository",
    contract: {
      signedAt: "2026-04-02T00:00:00.000Z",
      ownerContact: "library-systems@example.test",
      escalationContact: "research-it@example.test",
      sustainedRpm: 600,
      burstRpm: 1200,
      dailyExportLimit: 50000,
      concurrentJobs: 4,
      allowedEndpoints: ["/api/projects.read", "/api/publications.write", "/api/exports.zenodo"],
      allowedExportTargets: ["invenio", "zenodo"],
    },
    productionConfig: {
      sustainedRpm: 500,
      burstRpm: 900,
      dailyExportLimit: 40000,
      concurrentJobs: 3,
      endpoints: ["/api/projects.read", "/api/publications.write", "/api/exports.zenodo"],
      exportTargets: ["invenio", "zenodo"],
      enforcesRetryAfter: true,
      backoffMode: "exponential_jitter",
      requiresIdempotencyKey: true,
      privateProjectAccess: false,
    },
    webhook: {
      enabled: true,
      signingAlgorithm: "hmac-sha256",
      secretRotatedAt: "2026-05-01T00:00:00.000Z",
      deadLetterQueue: true,
      retryPolicy: { maxAttempts: 5 },
    },
    safeguards: {},
    evidence: {
      loadTestAt: "2026-05-10T00:00:00.000Z",
      dashboardTag: "LIBRARY-EXPORT",
    },
  },
  {
    id: "api-biocore-overlimit",
    name: "BioCore Bulk Export",
    institution: "BioCore Institute",
    integrationType: "external_archive",
    contract: {
      signedAt: "2026-03-12T00:00:00.000Z",
      ownerContact: "biocore-it@example.test",
      sustainedRpm: 300,
      burstRpm: 600,
      dailyExportLimit: 10000,
      concurrentJobs: 2,
      allowedEndpoints: ["/api/projects.read", "/api/exports.zenodo"],
      allowedExportTargets: ["zenodo"],
    },
    productionConfig: {
      sustainedRpm: 900,
      burstRpm: 2500,
      dailyExportLimit: 25000,
      concurrentJobs: 6,
      endpoints: ["/api/projects.read", "/api/exports.zenodo", "/api/admin.users.delete"],
      exportTargets: ["zenodo", "pubmed-central"],
      enforcesRetryAfter: false,
      backoffMode: "fixed_sleep",
      requiresIdempotencyKey: false,
      privateProjectAccess: true,
    },
    webhook: {
      enabled: true,
      signingAlgorithm: "none",
      retryPolicy: { maxAttempts: 20 },
    },
    safeguards: {
      ipAllowlist: [],
    },
    evidence: {},
  },
  {
    id: "api-canvas-passback-hold",
    name: "Canvas Grade Passback",
    institution: "East Valley University",
    integrationType: "learning_management_system",
    contract: {
      signedAt: "2026-02-01T00:00:00.000Z",
      ownerContact: "lms-admin@example.test",
      escalationContact: "registrar@example.test",
      sustainedRpm: 200,
      burstRpm: 400,
      dailyExportLimit: 5000,
      concurrentJobs: 1,
      allowedEndpoints: ["/api/projects.read", "/api/lms.gradebook.write"],
      allowedExportTargets: ["canvas"],
    },
    productionConfig: {
      sustainedRpm: 175,
      burstRpm: 350,
      dailyExportLimit: 4500,
      concurrentJobs: 1,
      endpoints: ["/api/projects.read", "/api/lms.gradebook.write"],
      exportTargets: ["canvas"],
      enforcesRetryAfter: true,
      backoffMode: "retry_after",
      requiresIdempotencyKey: false,
      privateProjectAccess: true,
    },
    webhook: {
      enabled: true,
      signingAlgorithm: "hmac-sha256",
      secretRotatedAt: "2025-09-01T00:00:00.000Z",
      deadLetterQueue: false,
      retryPolicy: { maxAttempts: 4 },
    },
    safeguards: {
      ipAllowlist: ["203.0.113.0/24"],
      adminReviewPacket: true,
    },
    evidence: {
      loadTestAt: "2025-11-15T00:00:00.000Z",
      dashboardTag: "LMS-PASSBACK",
    },
  },
  {
    id: "api-moodle-review",
    name: "Moodle Read Analytics",
    institution: "Cedar Climate College",
    integrationType: "learning_management_system",
    contract: {
      signedAt: "2026-04-15T00:00:00.000Z",
      ownerContact: "analytics@example.test",
      escalationContact: "research-it@example.test",
      sustainedRpm: 150,
      burstRpm: 300,
      dailyExportLimit: 2000,
      concurrentJobs: 1,
      allowedEndpoints: ["/api/projects.read", "/api/analytics.read"],
      allowedExportTargets: ["moodle"],
    },
    productionConfig: {
      sustainedRpm: 100,
      burstRpm: 200,
      dailyExportLimit: 1500,
      concurrentJobs: 1,
      endpoints: ["/api/projects.read", "/api/analytics.read"],
      exportTargets: ["moodle"],
      enforcesRetryAfter: true,
      backoffMode: "retry_after",
      requiresIdempotencyKey: false,
      privateProjectAccess: false,
    },
    webhook: {
      enabled: false,
    },
    safeguards: {},
    evidence: {
      loadTestAt: "2026-05-05T00:00:00.000Z",
    },
  },
];

module.exports = { sampleIntegrations };
